### ISSUE TITLE
heap-buffer-overflow by default in 'create' mode

### ISSUE THREAD

**Issue by asarubbo** [animetosho/par2cmdline-turbo#19]
On 1.1.0, if compiled with AddressSanitizer:

```
~ $ echo a > a
~ $ par2 create a.par2 a
Block size: 4
Source file count: 1
Source block count: 1
Recovery block count: 1
Recovery file count: 1

Opening: a
=================================================================
==1970==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000120 at pc 0x000000661ad8 bp 0x7fb4d70f5950 sp 0x7fb4d70f5948
READ of size 32 at 0x602000000120 thread T1 (gf_transfer)
    #0 0x661ad7 in partial_load /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/gf16_checksum_x86.h:82:20
    #1 0x661ad7 in gf16_checksum_blocku_avx2 /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/gf16_checksum_x86.h:119:20
    #2 0x661ad7 in gf16_prepare_packed /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/gf16_global.h:158:22
    #3 0x661ad7 in gf16_xor_prepare_packed_cksum_avx2 /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/gf16_xor_common_funcs.h:149:1
    #4 0x5bca9a in PAR2ProcCPU::transfer_slice(ThreadMessageQueue<void*>&) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/controller_cpu.cpp:245:5
    #5 0x5cb337 in std::function<void (ThreadMessageQueue<void*>&)>::operator()(ThreadMessageQueue<void*>&) const /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/std_function.h:591:9
    #6 0x5cb337 in MessageThread::thread_func(void*) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/threadqueue.h:304:3
    #7 0x7fb4d9ad2e4e in execute_native_thread_routine /var/tmp/portage/sys-devel/gcc-12.2.1_p20230428-r1/work/gcc-12-20230428/libstdc++-v3/src/c++11/thread.cc:82:18
    #8 0x7fb4d97d9f7b in start_thread /var/tmp/portage/sys-libs/glibc-2.37-r3/work/glibc-2.37/nptl/pthread_create.c:444:8
    #9 0x7fb4d985716b in clone3 /var/tmp/portage/sys-libs/glibc-2.37-r3/work/glibc-2.37/misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

0x602000000120 is located 0 bytes after 16-byte region [0x602000000110,0x602000000120)
allocated by thread T0 here:
    #0 0x4f550d in operator new(unsigned long) /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.5/work/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x5508a1 in Par2Creator::CreateCreatorPacket() /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/par2creator.cpp:404:19
    #2 0x549132 in Par2Creator::Process(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, unsigned long, unsigned int, Scheme, unsigned int, unsigned int) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/par2creator.cpp:177:8
    #3 0x522f7b in par2create(std::ostream&, std::ostream&, NoiseLevel, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, unsigned long, unsigned int, Scheme, unsigned int, unsigned int) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/libpar2.cpp:39:27
    #4 0x4f87aa in main /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/par2cmdline.cpp:62:11
    #5 0x7fb4d977b676 in __libc_start_call_main /var/tmp/portage/sys-libs/glibc-2.37-r3/work/glibc-2.37/csu/../sysdeps/nptl/libc_start_call_main.h:58:16

Thread T1 (gf_transfer) created by T0 here:
    #0 0x4a2b7a in __interceptor_pthread_create /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.5/work/compiler-rt/lib/asan/asan_interceptors.cpp:208:3
    #1 0x7fb4d9ad2f14 in __gthread_create /var/tmp/portage/sys-devel/gcc-12.2.1_p20230428-r1/work/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:663:35
    #2 0x7fb4d9ad2f14 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State>>, void (*)()) /var/tmp/portage/sys-devel/gcc-12.2.1_p20230428-r1/work/gcc-12-20230428/libstdc++-v3/src/c++11/thread.cc:147:37
    #3 0x5c6ee9 in MessageThread::send(void*) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/threadqueue.h:373:3
    #4 0x5c434c in std::future<void> PAR2ProcCPU::_addInput<unsigned short>(void const*, unsigned long, unsigned short, bool) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/controller_cpu.cpp:328:17
    #5 0x5c38b2 in PAR2ProcCPU::addInput(void const*, unsigned long, unsigned short, bool) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/controller_cpu.cpp:284:23
    #6 0x5aa489 in std::future<void> PAR2Proc::_addInput<unsigned short>(void const*, unsigned long, unsigned short, bool) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/controller.cpp:252:36
    #7 0x5a9ed2 in PAR2Proc::addInput(void const*, unsigned long, unsigned short, bool) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/controller.cpp:259:9
    #8 0x551b63 in Par2Creator::ProcessData(unsigned long, unsigned long) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/par2creator.cpp:777:39
    #9 0x5496a3 in Par2Creator::Process(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, unsigned long, unsigned int, Scheme, unsigned int, unsigned int) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/par2creator.cpp:215:12
    #10 0x522f7b in par2create(std::ostream&, std::ostream&, NoiseLevel, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, unsigned long, unsigned int, Scheme, unsigned int, unsigned int) /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/libpar2.cpp:39:27
    #11 0x4f87aa in main /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/src/par2cmdline.cpp:62:11
    #12 0x7fb4d977b676 in __libc_start_call_main /var/tmp/portage/sys-libs/glibc-2.37-r3/work/glibc-2.37/csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /var/tmp/portage/app-arch/par2cmdline-turbo-1.1.0/work/par2cmdline-turbo-1.1.0/parpar/gf16/gf16_checksum_x86.h:82:20 in partial_load
Shadow bytes around the buggy address:
  0x601ffffffe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x601fffffff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x601fffffff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x602000000000: fa fa fd fd fa fa fd fd fa fa fd fd fa fa 00 00
  0x602000000080: fa fa fd fa fa fa 00 00 fa fa fd fa fa fa 00 fa
=>0x602000000100: fa fa 00 00[fa]fa 00 00 fa fa 02 fa fa fa 02 fa
  0x602000000180: fa fa 02 fa fa fa 02 fa fa fa fd fd fa fa 00 00
  0x602000000200: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x602000000280: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x602000000300: fa fa 00 00 fa fa fa fa fa fa fa fa fa fa fa fa
  0x602000000380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1970==ABORTING
Aborted
```

**Comment by animetosho** [comment]
Thanks!

Can you try the latest Git code to see if it's now fixed?
